name: film
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  dio: ^5.8.0+1
  flutter_bloc: ^8.1.0
  equatable: ^2.0.0
  get_it: ^8.0.3
  dartz:
  flutter_native_splash: ^2.4.1
  flutter_screenutil:
  injectable: ^2.5.0
  freezed: ^2.2.0
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0
  logger:
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  confetti: ^0.7.0
  animations: ^2.0.7
  flutter_animate: ^4.1.1+1
  intl: ^0.18.1


dev_dependencies:
  injectable_generator: ^2.6.2
  build_runner: ^2.4.11
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/images/


  # example:
  fonts:
     - family: SpaceGrotesk
       fonts:
         - asset: assets/fonts/SpaceGrotesk-Regular.ttf
